app/models.py
from . import db, login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    phone_number = db.Column(db.String(255), index = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    password_hash = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User {self.username}'

class Admin(db.Model):
    __tablename__ = 'admin'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    password = db.Column(db.String(5))

    def __repr__(self):
        return f'Admin {self.name}'
    
class Order(db.Model):
    __tablename__ = 'orders'
    id = db.Column(db.Integer,primary_key = True)
    Quantity = db.Column(db.Integer)
    cost=db.Column(db.Integer)
    Description = db.Column(db.String(255))
    time = db.Column(db.DateTime, default = datetime.utcnow)
    clientID = db.Column(db.Integer, db.ForeignKey('users.id'))
    totalCost = db.Column(db.Integer)
    
    def save_order(self):
        db.session.add(self)
        db.session.commit()
        return orders
    def calculate_total_cost(self,quantity,prize):
        total = Quantity * cost
        return total(self.totalCost)
    
    def __repr__(self):
        return f'Order {self.totalCost}'
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField,SubmitField,StringField,SelectField
from wtforms.validators import Required 



class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')
    
class OrderForm(FlaskForm):
    Quantity = StringField('Pitch Title', validators=[Required()])
    Description = StringField('Your Pitch', validators=[Required()])
    category = SelectField('Category', choices=[('Hawaian','Hawaian'),('Something Meaty','Something Meaty'),('Chicken Peri Peri','Chicken Peri Peri')],validators=[Required()])
    cost = SubmitField('Add To Cart')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()
simple = SimpleMDE()

def create_app(config_name):

    app = Flask(__name__)
    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)
    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Will add the views and forms
    
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    configure_uploads(app,photos)
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error
from flask_uploads import UploadSet,configure_uploads,IMAGES


photos = UploadSet('photos',IMAGES)
def create_app(config_name):
    app = Flask(__name__)
    # configure UploadSet
    configure_uploads(app,photos)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import UpdateProfile,OrderForm
from ..models import User,Admin
from flask_login import login_required,current_user
from .. import db,photos
import markdown2  

@main.route('/')
def index():
    '''
    view root page function that returns index page
    '''
    title = 'Home'
    return render_template('index.html', title = title)

@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block styles%}
    {{ super() }}
{% endblock %}
{% block content %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>PIZZA</title>
    <!-- jquery-2.2.0 -->
    <!-- <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
    bootstrap w/ optional theme
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    my css and js
    <link rel="stylesheet" href="css/styles.css">
    <script type="text/javascript" src="js/scripts.js"></script> -->
  </head>
  <body>
    <div class="header page-header text-center">
      <h1>Pizza Tamu</h1>
    </div>
    <div class="container">
      <div class="order-pizza-input initially-hidden">
        <h3>Add a pizza to your order.</h3>
        <div class="row">
        <form>
          <div class="size form-group col-md-3">
            <h4>Pie Size:</h4>
            <label class="checkbox-inline"><input type="radio" name="pie-size" value="small"> Small ($7)</label>
            <label class="checkbox-inline"><input type="radio" name="pie-size" value="medium" checked> Medium ($9)</label>
            <label class="checkbox-inline"><input type="radio" name="pie-size" value="large"> Large ($11)</label>
            <label class="checkbox-inline"><input type="radio" name="pie-size" value="extra large"> Extra Large ($13)</label>
          </div>
          <div class="meat-toppings  form-group col-md-3">
            <h4>Meats: ($1.25 each) </h4>
            <label class="checkbox-inline">
              <input type="checkbox" name="meat-toppings" value="Pepperoni">Pepperoni
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="meat-toppings" value="Sausage">Sausage
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="meat-toppings" value="Ham">Ham
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="meat-toppings" value="Meatball">Meatball
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="meat-toppings" value="Hamburger">Hamburger
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="meat-toppings" value="Bacon">Bacon
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="meat-toppings" value="Grilled Chicken">Grilled Chicken
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="meat-toppings" value="Meat Surprise">Meat Surprise
            </label>
          </div>
          <div class="veg-toppings  form-group col-md-3">
            <h4>Veggies: ($0.75 each) </h4>
            <label class="checkbox-inline">
              <input type="checkbox" name="veg-toppings" value="Olives">Olives
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="veg-toppings" value="Tomatoes">Tomatoes
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="veg-toppings" value="Onions">Onions
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="veg-toppings" value="Green Peppers">Green Peppers
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="veg-toppings" value="Mushrooms">Mushrooms
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="veg-toppings" value="Basil">Basil
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="veg-toppings" value="Spinach">Spinach
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="veg-toppings" value="Banana Peppers">Banana Peppers
            </label>
            <label class="checkbox-inline">
              <input type="checkbox" name="veg-toppings" value="Pineapple">Pineapple
            </label>
          </div>
          <div class="cheese  form-group">
            <h4>Cheese:</h4>
            <label class="checkbox"><input type="radio" name="cheese-options" value="regular" checked>  Regular</label>
            <label class="checkbox"><input type="radio" name="cheese-options" value="extra">  Extra Cheese <em>(add $1)</em></label>
            <label class="checkbox"><input type="radio" name="cheese-options" value="none">  No Cheese</label>
          </div>
          <button type="submit" class="btn btn-success">Add Pizza</button>
        </form>
        </div>
      </div>
      <div class="order-summary initially-hidden">
        <h3>Your order.</h3>
        <p>Click on a pizza to view and hide more information.</p>
        <div class="pizza-list"></div>
        <h3>Total Cost: <span id="pizza-list-total-cost"></span></h3>
        <button id="add-another-pizza" class="btn btn-success">Add another Pizza</button>
        <button id="checkout-order" class="btn btn-success">Checkout Out</button>
      </div>
      <div class="checked-out  initially-hidden">
        <h3>Your order is on its way!</h3>
        <p>Click below to place a new order.</p>
        <button type="button" class="btn btn-success" id="new-order">New Order</button>
      </div>
    </div>
  </body>
</html>
{% endblock %}

app/templates/macros.html
{% macro displayCategories(category_list) %}
    
{% endmacro %}

{% macro displayPitches(pitch_list) %}
    
{% endmacro %}

{% macro displayReviews(review_list) %}
    
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/"> Pizza Tamu</a>
        <li><a href="{{url_for('auth.login')}}">Admin Panel</a></li>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
        </ul>                 
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li style="color:white;padding:15px;">{{current_user.username}}</li>
          <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
          <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
          {% else %}
          <li><a href="{{url_for('auth.register')}}">Register</a></li>
          <li class="divider"></li>
          <li><a href="{{url_for('auth.login')}}">Sign in</a></li>

          {% endif %}
        </ul>        
      </div>
    </div>
  </div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}